### PR TITLE
TypeScript Support

### PR DESCRIPTION
**Pull request by kuasha420**

### CODE REVIEW

**Comment by slhck** [comment]
Looks good to me, @fohletex what do you think?

**Comment by slhck** [comment]
Just for your information, @kuasha420 – we're currently performing some updates on internal code during which we will integrate and test your changes as well, so that's why it takes a bit longer to evaluate this PR. We hope to be able to merge it soon.

**Comment by kuasha420** [comment]
@slhck No problems at all.

**Comment by fohletex** [comment]
Looks okay - we should add an example app in order to improve the merge-speed of such requests. Thank you @kuasha420 for your inputs!

**Comment by fohletex** [comment]
Published in v2.0.0

**Pull request merged**
